In [ ]:
Python Exercise No:2
Subject:Arrays and String in python

In [ ]:
1. What is an array?
ans: An array is an object that stores a group of elements or (values) of same datatypes. Arrays can store only one type of data. for example - integer type value or string or character type values.

2. What is difference between array and list?
ans: List is similar to an array that consists of group of elements.A list can stores a group of elements of different datatypes.List do not have a fixed size.
An array is an object that stores a group of elements or (values) of same datatypes. Array have a fixed sized.

3. How to change the shape of an array?
ans: We can used reshape() function to change the shape of an array. for example- arr = arange(10)


In [1]:
import numpy as np
arr = np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
4. What does the name.strip () do?
ans: The strip() fuction is uesd to remove the space of a string from both left as well as right side.

In [4]:
a=" karishma "
a.strip()

'karishma'

In [ ]:
5. When we use triple single or triple double quotes to define a string?
ans: When we want to display the paragraph or to print multiple lines then we use single (''' ''') or double (""" """) triple quotes.

In [ ]:
6. Create a character type array?

In [5]:
import numpy as np
a=np.array(['a','b','c','d'])
print(a)
type(a)

['a' 'b' 'c' 'd']


numpy.ndarray

In [ ]:
7. Create a “hello”string and access the string character "ll" in python?

In [6]:
m="hello"
print(m)
print(m[2:4])

hello
ll


In [ ]:
8. Create an array to get largest and smallest number using minimum and maximum function?

In [8]:
a=np.array([12,14,67,89,79])
print(a)
b=min(a)
print(b)
c=max(a)
print(c)

[12 14 67 89 79]
12
89


In [ ]:
9. If name is “core python”then access the "python" from name and reverse "python" using slicing?

In [9]:
name="core python"
a=name[5:11]
print(a)
b=name[-1:-7:-1]
print(b)

python
nohtyp


In [ ]:
10. Create an array of integer type and add element 12 using append method and remove one element using remove methods

In [13]:
from array import *
arr1=array("i",[8,3,4,32,2])
arr1.append(12)                           #add element 12 using append method
arr1.remove(3)                              #delete element using remove method
arr1.remove(4)
print(arr1)

array('i', [8, 32, 2, 12])


In [ ]:
11. Create a single dimensional and 3 dimensional array using numpy?

In [17]:
import numpy as np
a1=np.array([2,3,6])                                      #arr1 is single dimensional array
a2=np.array([[4,5,6],[2,3,6],[1,2,6]])                    #arr2 is 3 dimensional array
print(a1)
print(a2)

[2 3 6]
[[4 5 6]
 [2 3 6]
 [1 2 6]]


In [ ]:
12. Create a “Programiz”string and convert the string into upper, lower case? And replace given string by “program”using replacemethod?

In [18]:
str="Programiz"
a=str.upper()
b=str.lower()
c=str.replace("Programiz","program")
print(a)
print(b)
print(c)

PROGRAMIZ
programiz
program


In [ ]:
13. Create a two array one using linspace and another using arange function and then subtract array1 from array 2?

In [19]:
from numpy import *
arr1=np.linspace(2,10,5)         #we create 5 numbers between 2 to 10
print(arr1)
arr2=np.arange(12,17,1)         #we create  5 number from 12 to 16 with 1 step
print(arr2)
sub=arr2-arr1
print(sub)

[ 2.  4.  6.  8. 10.]
[12 13 14 15 16]
[10.  9.  8.  7.  6.]


In [ ]:
14. Create a “happy new year”string and then separate this string by (space) ",”?

In [20]:
str1="happy new year"
d=str1.split(" ")                #Here we separate str1 by(space) " " .
print(d)
str2="happy:new:year"
d=str2.split(":")               #Here we separate str2 by(colon) ":" .
print(d)

['happy', 'new', 'year']
['happy', 'new', 'year']


In [ ]:
15. Create two string and check whether one string present in another string using membership operator?

In [21]:
#in and not in are membership operators in python.
str1="she is a girl"
str2="girl"
print(str2 in str1)
print(str2 not in str1)

True
False
