In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('train.csv')
testset = pd.read_csv("test.csv").drop(['Name','Ticket','Cabin'],axis=1) 

X_test = testset

X_train = dataset.drop(['Survived','Name','Ticket','Cabin'],axis=1)
y_train = dataset['Survived']

print(X_test)
print(X_train)


     PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.5      0      0    7.8292        Q
1            893       3  female  47.0      1      0    7.0000        S
2            894       2    male  62.0      0      0    9.6875        Q
3            895       3    male  27.0      0      0    8.6625        S
4            896       3  female  22.0      1      1   12.2875        S
..           ...     ...     ...   ...    ...    ...       ...      ...
413         1305       3    male   NaN      0      0    8.0500        S
414         1306       1  female  39.0      0      0  108.9000        C
415         1307       3    male  38.5      0      0    7.2500        S
416         1308       3    male   NaN      0      0    8.0500        S
417         1309       3    male   NaN      1      1   22.3583        C

[418 rows x 8 columns]
     PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0              1       3    male  22.0   

In [3]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer.fit(X_train[['Age']])
X_train['Age'] = imputer.transform(X_train[['Age']])

imputer.fit(X_test[['Age']])
X_test['Age'] = imputer.transform(X_test[['Age']])

imputer.fit(X_test[['Fare']])
X_test['Fare'] = imputer.transform(X_test[['Fare']])


imputer_text = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

imputer_text.fit(X_train[['Embarked']])
X_train['Embarked'] = imputer_text.transform(X_train[['Embarked']])

imputer_text.fit(X_test[['Embarked']])
X_test['Embarked'] = imputer_text.transform(X_test[['Embarked']])

print(X_test)
print(X_train)

     PassengerId  Pclass     Sex       Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.50000      0      0    7.8292        Q
1            893       3  female  47.00000      1      0    7.0000        S
2            894       2    male  62.00000      0      0    9.6875        Q
3            895       3    male  27.00000      0      0    8.6625        S
4            896       3  female  22.00000      1      1   12.2875        S
..           ...     ...     ...       ...    ...    ...       ...      ...
413         1305       3    male  30.27259      0      0    8.0500        S
414         1306       1  female  39.00000      0      0  108.9000        C
415         1307       3    male  38.50000      0      0    7.2500        S
416         1308       3    male  30.27259      0      0    8.0500        S
417         1309       3    male  30.27259      1      1   22.3583        C

[418 rows x 8 columns]
     PassengerId  Pclass     Sex        Age  SibSp  Parch     Fa

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,7])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))
X_test = np.array(ct.fit_transform(X_test))

print(X_test)

[[ 0.      0.      1.     ...  0.      0.      7.8292]
 [ 0.      0.      1.     ...  1.      0.      7.    ]
 [ 0.      1.      0.     ...  0.      0.      9.6875]
 ...
 [ 0.      0.      1.     ...  0.      0.      7.25  ]
 [ 0.      0.      1.     ...  0.      0.      8.05  ]
 [ 0.      0.      1.     ...  1.      1.     22.3583]]


In [5]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

c:\users\win7\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [6]:
y_pred = classifier.predict(X_test)

In [7]:
output = pd.DataFrame({'PassengerId': testset.PassengerId, 'Survived': y_pred})
output.to_csv('my_submission.csv', index=False)